import type { TrackType } from '@onsemetbien/shared';

/**
 * A track ready to be scheduled/played. Contains metadata only — the `url`
 * field is the raw storage key/filename, NOT a signed URL. Signed URLs are
 * generated by the caller at play time.
 */
export interface ScheduledTrack {
  _id: string;
  title: string;
  type: TrackType;
  duration?: number;
  url: string;
}

/**
 * Dependencies injected into the scheduler. Every side effect (DB, S3, RNG for
 * deck order) lives here so the scheduler itself is pure and unit-testable with
 * no database and no S3.
 */
export interface SchedulerDeps {
  /** Shuffled track ids for a type (hidden already excluded). */
  loadDeck(type: TrackType): Promise<string[]>;
  /** Number of playable tracks of a type. */
  countByType(type: TrackType): Promise<number>;
  /** Metadata for a track (no signed url); `url` is the raw storage key. */
  loadTrack(id: string): Promise<ScheduledTrack | null>;
  /** Whether a track still exists and is not hidden (handles stale deck ids). */
  isPlayable(id: string): Promise<boolean>;
}

export interface SchedulerOptions {
  /** How many tracks to keep queued ahead of the current one. Default 6. */
  lookahead?: number;
}

const ALL_TYPES: readonly TrackType[] = ['music', 'excerpt', 'sketch', 'jingle'];

/** Max stale-id skips per generated item before giving up on a type. */
const MAX_DRAW_ATTEMPTS = 3;

/**
 * Generates the "programme à venir" as a lookahead queue while preserving the
 * existing variety rules (never the same type twice in a row; prefer music
 * after a non-music track) and the shuffled-deck guarantee (every track of a
 * type plays once before any repeat).
 */
export class RadioScheduler {
  private readonly deps: SchedulerDeps;
  private readonly lookahead: number;

  private readonly decks: Record<TrackType, string[]> = {
    music: [],
    excerpt: [],
    sketch: [],
    jingle: [],
  };

  private queue: ScheduledTrack[] = [];

  // Variety is enforced against the tail of what has already been queued so the
  // whole generated sequence obeys the rules, not just the currently-playing
  // track. Falls back to the last actually-played track when the queue is empty.
  private lastQueuedType: TrackType | null = null;
  private lastQueuedId: string | null = null;
  private lastPlayedType: TrackType | null = null;
  private lastPlayedId: string | null = null;

  constructor(deps: SchedulerDeps, options: SchedulerOptions = {}) {
    this.deps = deps;
    this.lookahead = options.lookahead ?? 6;
  }

  /**
   * Append generated tracks until the queue reaches `minSize`. Bounded so it
   * never loops forever when there is nothing (playable) to schedule.
   */
  async ensureQueue(minSize: number): Promise<void> {
    // Each generated item may burn a handful of draw attempts; bound the outer
    // loop generously but finitely so an empty catalogue terminates fast.
    const maxIterations = minSize * ALL_TYPES.length + ALL_TYPES.length;
    let iterations = 0;

    while (this.queue.length < minSize && iterations < maxIterations) {
      iterations++;
      const track = await this.generateOne();
      if (!track) break; // Nothing playable right now — stop rather than spin.
      this.queue.push(track);
    }
  }

  /**
   * Ensure at least one track is queued, pop it as the now-playing track,
   * record it as last-played, then top the queue back up to the lookahead size.
   * Resolves to null when nothing is playable.
   */
  async advance(): Promise<ScheduledTrack | null> {
    await this.ensureQueue(1);

    const track = this.queue.shift();
    if (!track) return null;

    this.lastPlayedType = track.type;
    this.lastPlayedId = track._id;

    await this.ensureQueue(this.lookahead);
    return track;
  }

  /** The next `count` items currently queued, without consuming them. */
  peekUpcoming(count: number): ScheduledTrack[] {
    return this.queue.slice(0, count);
  }

  // --- internals ---------------------------------------------------------

  private async generateOne(): Promise<ScheduledTrack | null> {
    const refType = this.lastQueuedType ?? this.lastPlayedType;
    const type = await this.pickNextType(refType);
    if (!type) return null;

    let id: string | null = null;
    for (let attempt = 0; attempt < MAX_DRAW_ATTEMPTS && !id; attempt++) {
      const candidate = await this.drawFromDeck(type);
      if (!candidate) break;

      if (await this.deps.isPlayable(candidate)) {
        id = candidate;
      } else {
        // Stale deck entry (deleted/hidden since the deck was shuffled): drop
        // the whole deck so the next draw refills from a fresh source.
        this.decks[type] = [];
      }
    }

    if (!id) return null;

    const track = await this.deps.loadTrack(id);
    if (!track) return null;

    this.lastQueuedType = track.type;
    this.lastQueuedId = track._id;
    return track;
  }

  /**
   * Port of the original `pickNextType` variety logic, evaluated against a
   * reference type (the last-queued type, falling back to last-played).
   */
  private async pickNextType(refType: TrackType | null): Promise<TrackType | null> {
    const typesWithTracks: TrackType[] = [];
    for (const type of ALL_TYPES) {
      if (this.decks[type].length > 0) {
        typesWithTracks.push(type);
        continue;
      }
      if ((await this.deps.countByType(type)) > 0) {
        typesWithTracks.push(type);
      }
    }

    if (typesWithTracks.length === 0) return null;

    // Prefer music after a non-music track.
    if (refType && refType !== 'music' && typesWithTracks.includes('music')) {
      return 'music';
    }

    // Otherwise pick any type that isn't the same as the reference one.
    const candidates = typesWithTracks.filter((t) => t !== refType);
    const pool = candidates.length > 0 ? candidates : typesWithTracks;
    return pool[Math.floor(Math.random() * pool.length)] ?? null;
  }

  private async drawFromDeck(type: TrackType): Promise<string | null> {
    if (this.decks[type].length === 0) {
      this.decks[type] = await this.deps.loadDeck(type);
    }
    if (this.decks[type].length === 0) return null;

    let id = this.decks[type].shift();
    if (id === undefined) return null;

    // Avoid handing back the exact track we just queued/played — only possible
    // right after a refill where the first card equals the previous one.
    const avoid = this.lastQueuedId ?? this.lastPlayedId;
    if (id === avoid && this.decks[type].length > 0) {
      this.decks[type].push(id);
      const next = this.decks[type].shift();
      if (next !== undefined) id = next;
    }

    return id;
  }
}
