import dotenv from 'dotenv';
import path from 'path';
// Load environment variables from the monorepo root .env file
dotenv.config({ path: path.resolve(__dirname, '..', '..', '..', '.env') });

import { GetObjectCommand, S3Client } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import express from 'express';
import { createServer } from 'http';
import { Server } from 'socket.io';
import { connectToDatabase, TrackModel, TrackType } from '@onsemetbien/shared';
import { RadioScheduler, ScheduledTrack, SchedulerDeps } from './scheduler';

const app = express();
const httpServer = createServer(app);
const io = new Server(httpServer);

const s3Client = new S3Client({
  region: process.env.OVH_REGION || 'eu-west-par',
  endpoint: `https://s3.${process.env.OVH_REGION}.io.cloud.ovh.net`,
  credentials: {
    accessKeyId: process.env.OVH_ACCESS_KEY_ID || '',
    secretAccessKey: process.env.OVH_SECRET_ACCESS_KEY || '',
  },
  forcePathStyle: true,
});

const DEFAULT_DURATION = 300; // seconds, used when a track has no stored duration
const LOOKAHEAD = 6; // tracks kept ahead of the current one
const UPCOMING_COUNT = 5; // "programme à venir" size sent to clients

let currentTrack: ScheduledTrack | null = null;
let listeners = 0;
let currentTrackStartTime: number = Date.now();
let skipVotes = new Set<string>();
let currentTrackTimeout: NodeJS.Timeout | null = null;

function shuffle<T>(arr: T[]): T[] {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j]!, a[i]!];
  }
  return a;
}

/**
 * Bridge the pure scheduler to MongoDB. Shuffled decks, counts, metadata and
 * playability checks all come from `TrackModel`. No S3 here — signed URLs are
 * generated by the caller at play time.
 */
const schedulerDeps: SchedulerDeps = {
  async loadDeck(type: TrackType): Promise<string[]> {
    const tracks = await TrackModel.find({ type, hidden: { $ne: true } })
      .select('_id')
      .lean();
    return shuffle(tracks.map((t) => t._id.toString()));
  },
  async countByType(type: TrackType): Promise<number> {
    return TrackModel.countDocuments({ type, hidden: { $ne: true } });
  },
  async loadTrack(id: string): Promise<ScheduledTrack | null> {
    const track = await TrackModel.findById(id)
      .select('title url duration type _id')
      .lean();
    if (!track) return null;
    return {
      _id: track._id.toString(),
      title: track.title,
      type: track.type as TrackType,
      duration: track.duration,
      url: track.url,
    };
  },
  async isPlayable(id: string): Promise<boolean> {
    const exists = await TrackModel.exists({ _id: id, hidden: { $ne: true } });
    return Boolean(exists);
  },
};

const scheduler = new RadioScheduler(schedulerDeps, { lookahead: LOOKAHEAD });

async function getSignedS3Url(key: string): Promise<string> {
  // Only the filename is stored as the S3 object key.
  const filename = key.split('/').pop() || key;
  const command = new GetObjectCommand({
    Bucket: process.env.OVH_BUCKET,
    Key: filename,
  });
  // URL expires in 1 hour.
  return getSignedUrl(s3Client, command, { expiresIn: 3600 });
}

function trackDurationOf(track: ScheduledTrack): number {
  return track.duration && track.duration > 0 ? track.duration : DEFAULT_DURATION;
}

/** The "programme à venir": next tracks metadata (no URLs). */
function buildUpcomingPayload(): {
  tracks: Array<{ title: string; type: TrackType; duration?: number }>;
} {
  return {
    tracks: scheduler.peekUpcoming(UPCOMING_COUNT).map((t) => ({
      title: t.title,
      type: t.type,
      duration: t.duration,
    })),
  };
}

/** Signed URL of the next queued track for gapless preloading (or null). */
async function buildPreloadPayload(): Promise<{ url: string | null }> {
  const next = scheduler.peekUpcoming(1)[0];
  if (!next) return { url: null };
  return { url: await getSignedS3Url(next.url) };
}

/**
 * Advance to the next track: pick it from the scheduler, sign its URL, update
 * state, emit the enriched contract (trackChange + preloadNext + upcoming) and
 * schedule the following advance after the track's duration.
 */
async function playNextTrack(): Promise<void> {
  const nextTrack = await scheduler.advance();

  if (!nextTrack) {
    if (currentTrackTimeout) clearTimeout(currentTrackTimeout);
    console.log('No track available, retrying in 5 seconds...');
    currentTrackTimeout = setTimeout(playNextTrack, 5000);
    return;
  }

  if (currentTrackTimeout) {
    clearTimeout(currentTrackTimeout);
    currentTrackTimeout = null;
  }

  currentTrack = nextTrack;
  currentTrackStartTime = Date.now();
  skipVotes.clear();

  const signedUrl = await getSignedS3Url(currentTrack.url);
  const duration = trackDurationOf(currentTrack);

  io.emit('trackChange', {
    title: currentTrack.title,
    url: signedUrl,
    type: currentTrack.type,
    startTime: currentTrackStartTime,
    duration,
    skipVotes: 0,
  });

  io.emit('skipVotesUpdate', {
    votes: 0,
    required: Math.ceil(listeners * 0.5),
  });

  io.emit('preloadNext', await buildPreloadPayload());
  io.emit('upcoming', buildUpcomingPayload());

  console.log(
    `Now playing: ${currentTrack.title} (${currentTrack.type}) — next in ${duration}s`
  );

  currentTrackTimeout = setTimeout(playNextTrack, duration * 1000);
}

io.on('connection', async (socket) => {
  listeners++;
  io.emit('listenersUpdate', listeners);

  if (currentTrack) {
    const signedUrl = await getSignedS3Url(currentTrack.url);
    const currentPosition = (Date.now() - currentTrackStartTime) / 1000;

    socket.emit('trackChange', {
      title: currentTrack.title,
      url: signedUrl,
      type: currentTrack.type,
      startTime: currentTrackStartTime,
      duration: trackDurationOf(currentTrack),
      currentPosition,
      skipVotes: skipVotes.size,
    });

    socket.emit('preloadNext', await buildPreloadPayload());
    socket.emit('upcoming', buildUpcomingPayload());
  }

  socket.on('voteSkip', () => {
    skipVotes.add(socket.id);
    const voteCount = skipVotes.size;
    const requiredVotes = Math.ceil(listeners * 0.5); // 50% of listeners

    io.emit('skipVotesUpdate', {
      votes: voteCount,
      required: requiredVotes,
    });

    if (voteCount >= requiredVotes) {
      console.log('Skip threshold reached, playing next track...');
      skipVotes.clear();
      // playNextTrack emits fresh trackChange + preloadNext + upcoming.
      void playNextTrack();
    }
  });

  socket.on('disconnect', () => {
    listeners--;
    skipVotes.delete(socket.id);
    io.emit('listenersUpdate', listeners);
    io.emit('skipVotesUpdate', {
      votes: skipVotes.size,
      required: Math.ceil(listeners * 0.5),
    });
  });
});

// Serve the Vite-built client (dist/client/ when compiled, src/client/ in dev)
const clientDistPath = path.join(__dirname, 'client');
app.use(express.static(clientDistPath));
app.use(express.static('public'));

app.get('/health', (req, res) => {
  res.send('OK');
});

const PORT = process.env.PORT || 3001;

connectToDatabase().then(() => {
  httpServer.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`);
    void playNextTrack();
  });
});
